In [38]:
import csv
import pandas as pd

df = pd.read_csv('places.csv')
df['address'] = df['address_street']
for index, row in df.iterrows():
  address = "\"street\":\"{street}\", \"unit\":\"{unit}\", \"building\":\"{building}\", \"postal\":\"{postal}\""
  df.at[index, 'address'] = address.format(street=row['address_street'], unit=row['address_unit'], building=row['address_building'], postal=str(row['address_postal']))
df = df.drop(columns=['address_street', 'address_unit', 'address_building', 'address_postal'])

df['id'] = df['id'].apply(lambda x: "('" + x + "'")
df['name'] = df['name'].apply(lambda x: "'" + x + "'")
df['isHalal'] = df['isHalal'].apply(lambda x: str(x).upper() + "),")
df['address'] = df['address'].apply(lambda x: "'{" + x + "}'")

df['final'] = df['id'] + "," + df['name'] + "," + df['address'] + "," + df['isHalal']

df = df.drop(columns=['id', 'name', 'isHalal', 'address'])

df.to_csv('places-cleaned.csv', index=None, header=None)

df.head()

                                               final
0  ('876da698-4572-4bab-8376-045f17fa47bf','Sin K...
1  ('81a39830-80aa-4b35-9119-f6a356f396cd','Found...
2  ('3fb46d91-dafc-4f2c-8bc9-e21d9e4f6414','Seatt...
3  ('7158617e-72db-438f-a01e-ffe76ce622ae','Tan S...
4  ('870648fa-680f-4b42-bf42-af39fcd2baf5','Long ...

In [5]:
import pandas as pd

df = pd.read_csv('visits.csv')
df['id'] = df['id'].apply(lambda x: "('" + x + "'")
df['PlaceId'] = df['PlaceId'].apply(lambda x: "'" + x + "'")
df['isSponsored'] = df['isSponsored'].apply(lambda x: str(x).upper())
df['rating'] = df['rating'].apply(lambda x: str(x).upper())
df['youtubeUrl'] = df['youtubeUrl'].apply(lambda x: "'" + x + "'")
df['dateOfUpload'] = df['dateOfUpload'].apply(lambda x: "'" + x + "'),")

df['final'] = df['id'] + "," + df['PlaceId'] + "," + df['isSponsored'] + "," + df['rating'] + "," + df['youtubeUrl'] + "," + df['dateOfUpload']

df = df.drop(columns=['id', 'PlaceId', 'isSponsored', 'rating', 'youtubeUrl', 'dateOfUpload'])

df.to_csv('visits-cleaned.csv', index=None, header=None)

df.head()

                                               final
0  ('44c3fd34-735f-4822-9043-9de45ba08524','876da...
1  ('7077d342-9bfd-48a9-9ebd-67eabc18f166','81a39...
2  ('d2f8bff2-9290-4767-bd8b-9cec432e4f40','3fb46...
3  ('30aae1df-0ae0-4177-8526-602b5f753086','71586...
4  ('ad803cce-4ebe-4628-88b4-9d1591bb3c6c','87064...

In [12]:
import pandas as pd

df = pd.read_csv('food.csv')

df.fillna('null', inplace=True)

df['PlaceId'] = df['PlaceId'].apply(lambda x: "('" + x + "'")
df['VisitId'] = df['VisitId'].apply(lambda x: "'" + x + "'")
df['hasPriceRange'] = df['hasPriceRange'].apply(lambda x: str(x).upper())
df['priceMin'] = df['priceMin'].apply(lambda x: str(x))
df['priceMax'] = df['priceMax'].apply(lambda x: str(x))
df['notes'] = df['notes'].apply(lambda x: "'" + x + "'")
df['name'] = df['name'].apply(lambda x: "'" + x + "'")
df['currency'] = df['currency'].apply(lambda x: "'" + x + "'),")

df['final'] = df['PlaceId'] + "," + df['VisitId'] + "," + df['hasPriceRange'] + "," + df['priceMin'] + "," + df['priceMax'] + "," + df['notes'] + "," + df['name'] + "," + df['currency']

df = df.drop(columns=['PlaceId', 'VisitId', 'hasPriceRange', 'priceMin', 'priceMax', 'notes', 'name', 'currency'])

df.to_csv('food-cleaned.csv', index=None, header=None)

df.head()

                                               final
0  ('876da698-4572-4bab-8376-045f17fa47bf','44c3f...
1  ('81a39830-80aa-4b35-9119-f6a356f396cd','7077d...
2  ('3fb46d91-dafc-4f2c-8bc9-e21d9e4f6414','d2f8b...
3  ('3fb46d91-dafc-4f2c-8bc9-e21d9e4f6414','d2f8b...
4  ('7158617e-72db-438f-a01e-ffe76ce622ae','71586...